version: '3'
services:
  appdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: folkders-dev
    volumes:
      - ./db:/var/lib/mysql
  app:
    build: ./docker
    volumes:
      - ./:/var/www/folkders
    ports:
      - 5000
    links:
      - appdb:appdb
  nginx:
    build: ./docker/nginx
    links:
      - app:app
    ports:
      - 80:80
      - 443:443
